version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=jota_news.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/jota_news
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jota_news
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A jota_news worker -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=jota_news.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/jota_news
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A jota_news beat -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=jota_news.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/jota_news
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

volumes:
  postgres_data: 