# Generated by Django 5.0.2 on 2025-05-22 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='vertical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.vertical'),
        ),
    ]
