# Generated by Django 5.0.2 on 2025-05-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_category_alter_news_vertical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
