name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: jota_news:latest
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Tag and push Docker image
        run: |
          docker tag jota_news:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
          
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp docker-compose.yml deploy/
          cp .env.example deploy/.env
          cp -r jota_news deploy/
          cp -r news deploy/
          cp -r users deploy/
          cp manage.py deploy/
          cp requirements.txt deploy/
          
      - name: Create deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deploy/
          retention-days: 5 